### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by TheClimbing** [NL-4-DEVS/Parkour#34]
I get this error when tapping a Checkpoint sign
`[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'Parkour v3': Call to a member function getText() on array on Parkour\Main
[19:33:01] [Server thread/CRITICAL]: Error: "Call to a member function getText() on array" (EXCEPTION) in "/phar_Parkour-master_2e2vQJ2eY0Hrap1.phar/src/Parkour/Main" at line 56
[19:33:01] [Server thread/DEBUG]: #0 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(Parkour\Main object, pocketmine\event\player\PlayerInteractEvent object)
[19:33:01] [Server thread/DEBUG]: #1 /src/pocketmine/plugin/PluginManager(707): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerInteractEvent object)
[19:33:01] [Server thread/DEBUG]: #2 /src/pocketmine/level/Level(1779): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerInteractEvent object)
[19:33:01] [Server thread/DEBUG]: #3 /src/pocketmine/Player(2297): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 Vector3(x=1072,y=1,z=1107), pocketmine\item\ItemBlock Item Air (0:0)x0, integer 1, double 0.9871, double 1, double 0.1632, pocketmine\Player Player(1))
[19:33:01] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(253): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\UseItemPacket object)
[19:33:01] [Server thread/DEBUG]: #5 /src/pocketmine/Player(2097): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, pocketmine\Player Player(1))
[19:33:01] [Server thread/DEBUG]: #6 /src/pocketmine/network/RakLibInterface(139): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
[19:33:01] [Server thread/DEBUG]: #7 /src/raklib/server/ServerHandler(94): pocketmine\network\RakLibInterface->handleEncapsulated(string 89.25.100.216:19132, raklib\protocol\EncapsulatedPacket `..D..?...../x.c.abPR~ ..L...aC.=.C.=.....s...:u.........B.!, integer 0)
[19:33:01] [Server thread/DEBUG]: #8 /src/pocketmine/network/RakLibInterface(74): raklib\server\ServerHandler->handlePacket(boolean)
[19:33:01] [Server thread/DEBUG]: #9 /src/pocketmine/network/Network(156): pocketmine\network\RakLibInterface->process(boolean)
[19:33:01] [Server thread/DEBUG]: #10 /src/pocketmine/Server(2644): pocketmine\network\Network->processInterfaces(boolean)
[19:33:01] [Server thread/DEBUG]: #11 /src/pocketmine/Server(2378): pocketmine\Server->tick(boolean)
[19:33:01] [Server thread/DEBUG]: #12 /src/pocketmine/Server(2256): pocketmine\Server->tickProcessor(boolean)
[19:33:01] [Server thread/DEBUG]: #13 /src/pocketmine/Server(1860): pocketmine\Server->start(boolean)
[19:33:01] [Server thread/DEBUG]: #14 /src/pocketmine/PocketMine(478): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\Genisys.phar/, string C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\, string C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\plugins\)
[19:33:01] [Server thread/DEBUG]: #15 (1): require_once(string phar://C:/Users/TheClimbing/Desktop/Genisys_Unsuportted/Genisys.phar/src/pocketmine/PocketMine.php)`

**Comment by Driesboy** [comment]
use a release not a beta build

**Comment by Driesboy** [comment]
and after that commit??

**Comment by TheClimbing** [comment]
Also I get this after manually adding Parkour folder and configs
```
 [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in phar://C:/Users/TheClimbing/Desktop/Genisys_Unsuportted/Genisys.phar/src/pocketmine/Player.php on line 2237" (EXCEPTION) in "/src/pocketmine/Player" at line 3917
```

**Comment by Driesboy** [comment]
yeah i need to remake this plugin i will start today

**Comment by TheClimbing** [comment]
Thank you som much! I bet a lot of people including me need this plugin so much.

**Comment by Driesboy** [comment]
fixed?

**Comment by TheClimbing** [comment]
The config is still not creating itself.I had to manually add it.And still getting Trying to get property on non-object after tapping a sign and.After I fall to the void it teleports me to the main spawn because"there id no checckpoint"

**Comment by TheClimbing** [comment]
But using nether reactor core everything is fine except [Earn Reward] signs and with them [Checkpoint] signs

**Comment by TheClimbing** [comment]
But using nether reactor core everything is fine except [Earn Reward] signs and with them [Checkpoint] signs

**Comment by TheClimbing** [comment]
Someone? :'(

**Comment by Driesboy** [comment]
i need to rewrite this but i have free time next week
